kind: Service
apiVersion: v1
metadata:
  name: grafana
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
  
spec:
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 9090
